#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jarn.viewdoc
Version  : 2.1
Release  : 2
URL      : https://files.pythonhosted.org/packages/45/bc/4478eb64c190e0cd0177ddfcc949130eb4a2e5b2ba51cb33e6140a4361b3/jarn.viewdoc-2.1.zip
Source0  : https://files.pythonhosted.org/packages/45/bc/4478eb64c190e0cd0177ddfcc949130eb4a2e5b2ba51cb33e6140a4361b3/jarn.viewdoc-2.1.zip
Summary  : Python documentation viewer
Group    : Development/Tools
License  : BSD-2-Clause
Requires: jarn.viewdoc-bin = %{version}-%{release}
Requires: jarn.viewdoc-python = %{version}-%{release}
Requires: jarn.viewdoc-python3 = %{version}-%{release}
Requires: Pygments
Requires: docutils
Requires: setuptools
BuildRequires : Pygments
BuildRequires : buildreq-distutils3
BuildRequires : docutils
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
============
jarn.viewdoc
============
------------------------------------
Python documentation viewer
------------------------------------

%package bin
Summary: bin components for the jarn.viewdoc package.
Group: Binaries

%description bin
bin components for the jarn.viewdoc package.


%package python
Summary: python components for the jarn.viewdoc package.
Group: Default
Requires: jarn.viewdoc-python3 = %{version}-%{release}

%description python
python components for the jarn.viewdoc package.


%package python3
Summary: python3 components for the jarn.viewdoc package.
Group: Default
Requires: python3-core

%description python3
python3 components for the jarn.viewdoc package.


%prep
%setup -q -n jarn.viewdoc-2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1546660379
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/viewdoc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
